services:
  mysql:
    image: mysql:8.0
    container_name: imp_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: imp_assessment
      MYSQL_USER: imp
      MYSQL_PASSWORD: imp
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password", "--sql-mode=", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: imp_php
    volumes:
      - ./laravel:/var/www/html
    environment:
      - APP_ENV=local
    depends_on:
      - mysql

  nginx:
    image: nginx:1.25-alpine
    container_name: imp_nginx
    ports:
      - "8080:80"
    volumes:
      - ./laravel:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  composer:
    image: composer:2
    container_name: imp_composer
    working_dir: /var/www/html
    volumes:
      - ./laravel:/var/www/html
    entrypoint: ["composer"]

  node:
    image: node:20-alpine
    container_name: imp_node
    working_dir: /usr/src/app
    volumes:
      - ./nextjs:/usr/src/app
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]

volumes:
  db_data:
